import Nav from '../components/nav';
import Footer from '../components/footer'
import DownloadPage from '../components/downloadPage'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Download Darkblock Embed Script</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <DownloadPage />
        <Footer />
      </main>
    </>
  )
}
